/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./*.html', './pages/**/*.html'],
  theme: {
    screens: {
      sm: '480px',
      md: '768px',
      lg: '976px',
      xl: '1440px',
      xxl: '1560px',
      xxxl: "1882px",
      xxxxl:"1900px"
    },
    extend: {
      backgroundColor: {
        'search': '#F4F6F9',
        'main': "#F4F6F9",
        'primary': " #005EB8",
        'primary-dark': "#002554",
        'status-red': "rgba(229, 85, 79, 0.87)",
        'status-yellow': "rgba(255, 184, 0, 0.87)",
        'status-green': "#40C1AC",
        'unactiveTab': "#D3DAE1"
      },
      backgroundImage: {
        'primary-gradient': 'linear-gradient(53.03deg, #005EB8 15.44%, #2093B3 52.5%, #40C1AC 82.35%)',
        'secondry-gradient': 'linear-gradient(71.42deg, #8FA0B4 -4.57%, #002554 106.92%)',
        'Home': "url('../images/Home.svg')",
        'Home-hover': "url('../images/Home_hover.svg')",
        'Network': "url('../images/Network.svg')",
        'Network-hover': "url('../images/Attentions_hover.svg')",
        'Users': "url('../images/Users.svg')",
        'Users-hover': "url('../images/Users_hover.svg')",
        'NewsCEnter': "url('../images/NewsCEnter.svg')",
        'NewsCEnter-hover': "url('../images/NewsCEnter_hover.svg')",
        'Attentions': "url('../images/Attentions.svg')",
        'Attentions2-hover': "url('../images/Attentions2_hover.svg')",
        'Pictures': "url('../images/Pictures.svg')",
        'Pictures-hover': "url('../images/Pictures_hover.svg')", 
        'libraryIcon': "url('../images/libraryIcon.svg')",
        'libraryIcon-hover': "url('../images/LibraryIcon_hover.svg')",
        'user-pattern': "url('../images/updatesBAckground.svg')",
        'support' : "url('../images/customerSupport.svg')",
        'support-hover' : "url('../images/customerSupport_Hover.svg')",
        'hr' : "url('../images/HR.svg')",
        'hr-hover' : "url('../images/HR_hover.svg')",
        'itSupport' : "url('../images/ITSupport.svg')",
        'itSupport-hover' : "url('../images/IT Support_hover.svg')",
        'services' : "url('../images/services.svg')",
        'services-hover' : "url('../images/services_hover.svg')",
        'crm' : "url('../images/crm.svg')",
        'crm-hover' : "url('../images/crm_hover.svg')",
        'documents' : "url('../images/Documents.svg')",
        'documents-hover' : "url('../images/Documents_hover.svg')",
        'adaa' : "url('../images/adaa.svg')",
        'adaa-hover' : "url('../images/adaa_hover.svg')",
        'join' : "url('../images/join.svg')",
        'join-hover' : "url('../images/join_hover.svg')",
        'visitor' : "url('../images/visitor.svg')",
        'visitor-hover' : "url('../images/visitor_hover.svg')",
        'slider1': "url('../images/slider1.svg')",
        'slider2': "url('../images/slider2.svg')",
        'slider3': "url('../images/slider3.svg')",
        'downArrow': "url('../images/downArrow.svg')" 
      },
      colors: {
        "primary-text": "#002554",
        "primary-blue": "#005EB8",
        "secondry-text": "#90969E",
        'status-green': "#40C1AC",
        'status-gray': "#8FA0B4",
    },
      fontSize:{
      'xll': "10px"
    },
      width: {
      "10/10": "10%",
      "5%": "5%",
      "7%": "7%",
      "12%": "12%",
      "15%": "15%",
      "18%": "18%",
      "30%": "30%",
      "31%": "31%",
      "34%": "34%",
      "35%": "35%",
      "37%": "37%",
      "40%": "40%",
      "42%": "42%",
      "43%": "43%",
      "47%": "47%",
      "50%": "50%",
      "52%": "52%",
      "55%": "55%",
      "60%": "60%",
      "62%": "62%",
      "65%": "65%",
      "67%": "67%",
      "70%": "70%",
      "75%": "75%",
      "80%": "80%",
      "85%": "85%",
      "90%": "90%",
      "106%": "106%",
      "196%": "196%",
      "136": "136px",
      "240": "240px",
      "428": "428px",
      "634": "634px",
      "941": "914px",
      "max-width-screen": "1280px",
      "available": "-webkit-fill-available"
    },
      height: {
      "100": "100px",
      "121": "121px",
      "580": "580px",
      "610": "610px",
      "85%": "85%",
    },
    gap:{
      "0.1": "10px",
      "120px": "120px",
      "7.2": "2.75rem"
    },
    padding: {
      "90px": "90px",
      "26": "106px",
      "1.2rem": "1.2rem"
    },
    margin: {
      "min-2":"-2px", 
      "min-7":"-7px",
      "27px": "27px",
      "5.5": "5.5rem",
      "7/2": "7.2rem"
    }
    },
  },
  plugins: [],
}
